# This workflow is disabled to prevent conflicts with the main tournament creator
name: "Disabled - Create Lichess Tournaments"

on:
  # Disabled - no triggers
  workflow_dispatch:
    inputs:
      disabled:
        description: 'This workflow is disabled'
        required: false
        default: 'Use Realtest.yml instead'

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Disabled
        run: |
          echo "This workflow has been disabled to prevent conflicts"
          echo "Use the Professional Tournament Creator (Realtest.yml) instead"
          exit 1
